// @redemeine/sync - Edge Sync Runtime contracts

export {
  type NodeCapabilities,
  type NodeRole,
  type NodeIdentity,
  resolveRole,
  createNodeIdentity,
  createOriginCapabilities,
  createRelayCapabilities,
  createLeafCapabilities,
} from './capabilities';

export {
  type SyncLane,
  SYNC_LANES,
  type SelectorFilter,
  type EventStreamSelector,
  type ProjectionSelector,
  type MasterDataSelector,
  type ConfigurationSelector,
  type LaneSelector,
  selectorIdentityKey,
  type SyncManifest,
  type ManifestByLane,
  groupSelectorsByLane,
  type ManifestDelta,
  computeManifestDelta,
  type StreamAddedSignal,
  type StreamRemovedSignal,
  type ManifestLifecycleSignal,
  deriveLifecycleSignals,
  type RuleContext,
  type IManifestRuleEngine,
  type IManifestStore,
  deriveChildManifest,
} from './manifest';

export type {
  EventStatus,
  StoredEvent,
  AggregateSnapshot,
  NewEvent,
  SaveEventOptions,
  SaveEventResult,
  ConfirmResult,
  SupersedeResult,
  ReadStreamOptions,
  ISyncEventStore,
  CommandMetadata,
  QueuedCommand,
  ICommandQueue,
  Checkpoint,
  ICheckpointStore,
} from './store';

export {
  type ReconciliationResult,
  type ConfirmedOutcome,
  type SupersededOutcome,
  type NewOutcome,
  type AlreadyConfirmedOutcome,
  type ErrorOutcome,
  type AuthoritativeEvent,
  type EventMatcher,
  defaultEventMatcher,
  ReconciliationDispatcher,
  type EventApplier,
  type RebuildResult,
  rebuildFromConfirmed,
  type ProducedEvent,
  createPendingEvents,
} from './pending';
