// @redemeine/sync - Edge Sync Runtime contracts

export {
  type NodeCapabilities,
  type NodeRole,
  type NodeIdentity,
  resolveRole,
  createNodeIdentity,
  createOriginCapabilities,
  createRelayCapabilities,
  createLeafCapabilities,
} from './capabilities';

export {
  type SyncLane,
  SYNC_LANES,
  type SelectorFilter,
  type EventStreamSelector,
  type ProjectionSelector,
  type MasterDataSelector,
  type ConfigurationSelector,
  type LaneSelector,
  selectorIdentityKey,
  type SyncManifest,
  type ManifestByLane,
  groupSelectorsByLane,
  type ManifestDelta,
  computeManifestDelta,
  type StreamAddedSignal,
  type StreamRemovedSignal,
  type ManifestLifecycleSignal,
  deriveLifecycleSignals,
  type RuleContext,
  type IManifestRuleEngine,
  type IManifestStore,
  deriveChildManifest,
} from './manifest';

export type {
  EventStatus,
  StoredEvent,
  AggregateSnapshot,
  NewEvent,
  SaveEventOptions,
  SaveEventResult,
  ConfirmResult,
  SupersedeResult,
  ReadStreamOptions,
  ISyncEventStore,
  CommandMetadata,
  QueuedCommand,
  ICommandQueue,
  Checkpoint,
  ICheckpointStore,
} from './store';

export {
  type ReconciliationResult,
  type ConfirmedOutcome,
  type SupersededOutcome,
  type NewOutcome,
  type AlreadyConfirmedOutcome,
  type ErrorOutcome,
  type AuthoritativeEvent,
  type EventMatcher,
  defaultEventMatcher,
  ReconciliationDispatcher,
  type EventApplier,
  type RebuildResult,
  rebuildFromConfirmed,
  type ProducedEvent,
  createPendingEvents,
} from './pending';

export type {
  DownstreamEvent,
  EventStreamSnapshot,
  EventStreamEvents,
  EventStreamAdded,
  EventStreamRemoved,
  EventStreamEnvelope,
  ProjectionSnapshot,
  ProjectionDelta,
  ProjectionRemoved,
  ProjectionEnvelope,
  ConfigSnapshot,
  ConfigDelta,
  ConfigEnvelope,
  EventStreamFeedInput,
  ProjectionFeedInput,
  ConfigFeedInput,
  DownstreamSyncService,
  FeedEnvelopeListener,
  FeedConsumerOptions,
  EnvelopeProcessResult,
  ConsumeResult,
  EventStreamConsumer,
} from './downstream';

export { createEventStreamConsumer } from './downstream';

export {
  type UpstreamCommandMetadata,
  type UpstreamCommandEnvelope,
  type UpstreamBatchRequest,
  type AcceptedCommandResult,
  type RejectedCommandResult,
  type DuplicateCommandResult,
  type UpstreamCommandResult,
  type UpstreamBatchResult,
  type UpstreamSyncService,
  type ConnectionState,
  type ConnectionStateListener,
  type Unsubscribe,
  type IConnectionMonitor,
  type DrainResult,
  type DrainResultListener,
  type QueueDrainOptions,
  type QueueDrain,
  createQueueDrain,
} from './upstream';

export {
  type PendingEventSummary,
  type LaneLagMetrics,
  type SyncHealthMetrics,
  type ConnectionChangedAlert,
  type QueueDepthThresholdAlert,
  type SyncLagThresholdAlert,
  type PendingEventThresholdAlert,
  type SyncAlert,
  type IMetricSink,
  type HealthSnapshotDependencies,
  captureHealthSnapshot,
  type SyncHealthThresholds,
  defaultThresholds,
  checkThresholds,
} from './health';
