import { describeContract } from './reflector';
import type { Contract } from '@redemeine/kernel';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

export interface GenerateSchemaOptions {
    /** Output directory for generated schema files */
    outDir: string;
    /** Aggregate name used in describeContract */
    aggregateName: string;
    /** Whether to generate individual files per command/event (default: true) */
    individual?: boolean;
    /** Whether to generate the bundle file (default: true) */
    bundle?: boolean;
}

/**
 * Generates JSON Schema files from a redemeine Contract.
 *
 * Produces:
 * - A bundle file (`json.ts`) exporting all schemas in a map structure
 * - Individual files per command/event for granular imports
 *
 * File names match the resolved type string segments (snake_case).
 * For example, `attachment.register.command` → `commands/register.ts`
 * and `attachment.available_pending.event` → `events/available_pending.ts`
 */
export function generateSchemaFiles(contract: Contract, options: GenerateSchemaOptions): void {
    const { outDir, aggregateName, individual = true, bundle = true } = options;
    const described = describeContract(contract, aggregateName);

    if (bundle) {
        writeBundleFile(outDir, described);
    }

    if (individual) {
        writeIndividualFiles(outDir, 'commands', described.commands, aggregateName);
        writeIndividualFiles(outDir, 'events', described.events, aggregateName);
    }
}

function extractName(typeString: string, aggregateName: string, suffix: string): string {
    const prefix = aggregateName + '.';
    const suffixDot = '.' + suffix;
    if (typeString.startsWith(prefix) && typeString.endsWith(suffixDot)) {
        return typeString.slice(prefix.length, -suffixDot.length);
    }
    return typeString;
}

function writeBundleFile(outDir: string, described: ReturnType<typeof describeContract>): void {
    const content = `// GENERATED by redemeine generate-schemas — do not edit
export const jsonSchemas = ${JSON.stringify(described, null, 2)} as const;
`;
    ensureDir(outDir);
    writeFileSync(join(outDir, 'json.ts'), content, 'utf-8');
}

function writeIndividualFiles(
    outDir: string,
    kind: 'commands' | 'events',
    schemas: Record<string, unknown>,
    aggregateName: string
): void {
    const suffix = kind === 'commands' ? 'command' : 'event';
    const dir = join(outDir, 'json', kind);
    ensureDir(dir);

    for (const [typeString, schema] of Object.entries(schemas)) {
        const name = extractName(typeString, aggregateName, suffix);
        const content = `// GENERATED by redemeine generate-schemas — do not edit
export default ${JSON.stringify(schema, null, 2)} as const;
`;
        writeFileSync(join(dir, `${name}.ts`), content, 'utf-8');
    }
}

function ensureDir(dir: string): void {
    mkdirSync(dir, { recursive: true });
}
