import * as ts from 'typescript';
import { TypeToZodConverter } from './typeConverter';

export interface OutputOptions {
    includeState?: boolean;
}

/**
 * Assembles the final .ts file string with imports, shared schemas,
 * and command/event/state schema exports.
 *
 * Two-phase design: Phase 1 eagerly converts all types so that
 * converter.generatedShared and converter.imports are fully populated.
 * Phase 2 assembles the output string referencing those maps.
 */
export function generateOutput(
    converter: TypeToZodConverter,
    commandPayloads: Map<string, ts.Type>,
    eventPayloads: Map<string, ts.Type>,
    stateType: ts.Type | null,
    options: OutputOptions
): string {
    // --- Phase 1: convert all types eagerly to populate shared schemas & imports ---
    const commandEntries = [...commandPayloads].map(
        ([name, type]) => [name, converter.convert(type)] as const
    );
    const eventEntries = [...eventPayloads].map(
        ([name, type]) => [name, converter.convert(type)] as const
    );
    const stateZod = options.includeState !== false && stateType
        ? converter.convert(stateType)
        : null;

    // --- Phase 2: assemble output now that maps are populated ---
    let output = "// GENERATED by redemeine extract-schemas — do not edit\nimport { z } from 'zod';\n";

    for (const imp of converter.imports) {
        output += imp + '\n';
    }
    output += '\n';

    for (const [varName, zodCode] of converter.generatedShared) {
        output += `const ${varName} = ${zodCode};\n\n`;
    }

    output += 'export const commandSchemas = {\n';
    for (const [name, zodCode] of commandEntries) {
        output += `  ${name}: ${zodCode},\n`;
    }
    output += '} as const;\n\n';

    output += 'export const eventSchemas = {\n';
    for (const [name, zodCode] of eventEntries) {
        output += `  ${name}: ${zodCode},\n`;
    }
    output += '} as const;\n\n';

    if (stateZod) {
        output += `export const stateSchema = ${stateZod};\n`;
    }

    return output;
}
