import { describeContract } from './describeContract';
import type { Contract } from '@redemeine/kernel';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { schemaSource, validateSchemaFilename, validateSchemaPaths } from './schemaFileSafety';

export interface GenerateSchemaOptions {
    /** Output directory for generated schema files */
    outDir: string;
    /** Aggregate name used in describeContract */
    aggregateName: string;
    /** Whether to generate individual files per command/event (default: true) */
    individual?: boolean;
    /** Whether to generate the bundle file (default: true) */
    bundle?: boolean;
}

/**
 * Generates JSON Schema files from a redemeine Contract.
 *
 * Produces:
 * - A bundle file (`json.ts`) exporting all schemas in a map structure
 * - Individual files per command/event for granular imports
 *
 * File names match the resolved type string segments (snake_case).
 * For example, `attachment.register.command` → `commands/register.ts`
 * and `attachment.available_pending.event` → `events/available_pending.ts`
 */
export function generateSchemaFiles(contract: Contract, options: GenerateSchemaOptions): void {
    const { outDir, aggregateName, individual = true, bundle = true } = options;
    const described = describeContract(contract, aggregateName);

    const files: { path: string; content: string }[] = [];
    if (bundle) files.push({ path: join(outDir, 'json.ts'), content: `// GENERATED by redemeine generate-schemas — do not edit\nexport const jsonSchemas = ${schemaSource(described)} as const;\n` });
    if (individual) {
        files.push(...individualFiles(outDir, 'commands', described.commands, aggregateName));
        files.push(...individualFiles(outDir, 'events', described.events, aggregateName));
    }
    validateSchemaPaths(files.map(file => file.path));
    for (const file of files) {
        mkdirSync(dirname(file.path), { recursive: true });
        writeFileSync(file.path, file.content, 'utf-8');
    }
}

function extractName(typeString: string, aggregateName: string, suffix: string): string {
    const prefix = aggregateName + '.';
    const suffixDot = '.' + suffix;
    if (typeString.startsWith(prefix) && typeString.endsWith(suffixDot)) {
        return typeString.slice(prefix.length, -suffixDot.length);
    }
    return typeString;
}

function individualFiles(
    outDir: string,
    kind: 'commands' | 'events',
    schemas: Record<string, unknown>,
    aggregateName: string
) {
    const suffix = kind === 'commands' ? 'command' : 'event';
    const dir = join(outDir, 'json', kind);
    return Object.entries(schemas).map(([typeString, schema]) => {
        const name = extractName(typeString, aggregateName, suffix);
        validateSchemaFilename(name);
        const content = `// GENERATED by redemeine generate-schemas — do not edit
export default ${schemaSource(schema)} as const;
`;
        return { path: join(dir, `${name}.ts`), content };
    });
}
