import { generateSchemaFiles } from '../../src/cli/generateSchemaFiles';
import { Contract } from '../../packages/kernel/src/Contract';
import { z } from 'zod';
import { existsSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';

describe('generateSchemaFiles', () => {
    const testOutDir = join(__dirname, '__generated_test_output__');

    beforeEach(() => {
        if (existsSync(testOutDir)) {
            rmSync(testOutDir, { recursive: true });
        }
    });

    afterAll(() => {
        if (existsSync(testOutDir)) {
            rmSync(testOutDir, { recursive: true });
        }
    });

    function createTestContract(): Contract {
        const contract = new Contract();
        contract.addCommand('attachment.register.command', z.object({ id: z.string() }));
        contract.addCommand('attachment.amend_summary.command', z.object({ summary: z.string() }));
        contract.addEvent('attachment.registered.event', z.object({ id: z.string(), status: z.string() }));
        contract.addEvent('attachment.available_pending.event', z.object({ source: z.string() }));
        return contract;
    }

    it('should generate bundle file with all schemas', () => {
        const contract = createTestContract();
        generateSchemaFiles(contract, { outDir: testOutDir, aggregateName: 'attachment' });

        const bundlePath = join(testOutDir, 'json.ts');
        expect(existsSync(bundlePath)).toBe(true);

        const content = readFileSync(bundlePath, 'utf-8');
        expect(content).toContain('export const jsonSchemas');
        expect(content).toContain('attachment.register.command');
        expect(content).toContain('attachment.registered.event');
        expect(content).toContain('GENERATED by redemeine');
    });

    it('should generate individual command files with snake_case names', () => {
        const contract = createTestContract();
        generateSchemaFiles(contract, { outDir: testOutDir, aggregateName: 'attachment' });

        const registerPath = join(testOutDir, 'json', 'commands', 'register.ts');
        const amendPath = join(testOutDir, 'json', 'commands', 'amend_summary.ts');

        expect(existsSync(registerPath)).toBe(true);
        expect(existsSync(amendPath)).toBe(true);

        const content = readFileSync(registerPath, 'utf-8');
        expect(content).toContain('export default');
        expect(content).toContain('GENERATED by redemeine');
    });

    it('should generate individual event files with snake_case names', () => {
        const contract = createTestContract();
        generateSchemaFiles(contract, { outDir: testOutDir, aggregateName: 'attachment' });

        const registeredPath = join(testOutDir, 'json', 'events', 'registered.ts');
        const pendingPath = join(testOutDir, 'json', 'events', 'available_pending.ts');

        expect(existsSync(registeredPath)).toBe(true);
        expect(existsSync(pendingPath)).toBe(true);
    });

    it('should respect bundle-only option', () => {
        const contract = createTestContract();
        generateSchemaFiles(contract, { outDir: testOutDir, aggregateName: 'attachment', individual: false });

        expect(existsSync(join(testOutDir, 'json.ts'))).toBe(true);
        expect(existsSync(join(testOutDir, 'json'))).toBe(false);
    });

    it('should respect individual-only option', () => {
        const contract = createTestContract();
        generateSchemaFiles(contract, { outDir: testOutDir, aggregateName: 'attachment', bundle: false });

        expect(existsSync(join(testOutDir, 'json.ts'))).toBe(false);
        expect(existsSync(join(testOutDir, 'json', 'commands'))).toBe(true);
        expect(existsSync(join(testOutDir, 'json', 'events'))).toBe(true);
    });
});
