import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 1. The main documentation sidebar (Tutorials, Guides, etc.)
  docsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: ['tutorials/essentials'],
    },
    {
      type: 'category',
      label: 'Usage with TypeScript',
      items: ['usage-with-typescript/typescript-patterns'],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: ['concepts/immer-and-mutations', 'concepts/path-aware-routing'],
    },
    {
      type: 'category',
      label: 'Guides & Architecture',
      items: ['guides/path-conventions', 'guides/zod-integration', 'architecture/decision-log'],
    },
    {
      type: 'category',
      label: 'Recipes',
      items: ['recipes/testing-aggregates'],
    },
  ],

  // 2. The dedicated API sidebar (Auto-generated)
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api', // Points to the docs/api folder generated by TypeDoc
    },
  ],
};

export default sidebars;